apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pod-pruner
rules:
  - apiGroups: ['']
    resources: ['pods']
    verbs: ['list', 'delete']
  - apiGroups: ['']
    resources: ['pods/eviction']
    verbs: ['create']
  - apiGroups: ['batch']
    resources: ['jobs']
    verbs: ['list', 'delete']
