apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pod-pruner
  labels:
    app.kubernetes.net/name: pod-pruner
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pod-pruner
subjects:
  - kind: ServiceAccount
    name: pod-pruner
    namespace: pod-pruner
