apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pod-pruner
rules:
  - apiGroups: ['']
    resources: ['pods']
    verbs: ['get', 'list', 'delete']
  - apiGroups: ['']
    resources: ['pods/eviction']
    verbs: ['create']
  - apiGroups: ['batch']
    resources: ['jobs']
    verbs: ['get', 'list', 'delete']
  - apiGroups: ['']
    resources: ['nodes', 'pods']
    verbs: ['get', 'list']
  - apiGroups: ['metrics.k8s.io']
    resources: ['nodes', 'pods']
    verbs: ['get', 'list']
