apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.net/name: pod-pruner
  name: pod-pruner
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app.kubernetes.net/name: pod-pruner
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.net/name: pod-pruner
      annotations:
        prometheus.io/port: "8080"
        prometheus.io/scrape: "true"
    spec:
      containers:
        - env:
            - name: NAMESPACES
              value: 'argocd'
            - name: CONTAINER_STATUSES
              value: 'Error,ContainerStatusUnknown,Unknown,Completed'
            - name: RESOURCES
              value: 'PODS,JOBS'
          image: 'ghcr.io/saidsef/pod-pruner:latest'
          imagePullPolicy: Always
          name: pod-pruner
          resources:
            limits:
              cpu: 10m
              memory: 20Mi
            requests:
              cpu: 5m
              memory: 10Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1000
      dnsPolicy: ClusterFirst
      securityContext: {}
      serviceAccountName: pod-pruner
      terminationGracePeriodSeconds: 30
